### PR TITLE
BUG: fix #42

### LINKED ISSUE #42: Failure to delete evidenceURL in DPG files
The code does not delete `evidenceURL` fields from the DPG submission.

### PR DESCRIPTION
**Pull request by lacabra**
Fixes #42.

For a submission that included relevance to SDGs 1, 2 and 3 with the following fields:

```
  "SDGs": [
    {
      "SDGNumber": 1,
      "evidenceText": "description1",
      "evidenceURL": "http://example.com/1"
    },
    {
      "SDGNumber": 2,
      "evidenceText": "description2"
    },
    {
      "SDGNumber": 3,
      "evidenceURL": "http://example.com/3"
    }
```

The old code generate this faulty PR: lacabra/publicgoods-candidates#10 (which was running an older version of master before the PR submission was split into two), after this fix, these are two valid PRs:
* lacabra/publicgoods-candidates/pull/15
* lacabra/publicgoods-candidates/pull/16

### CODE REVIEW

File: pages/api/openPR.js [hunk 1]
```diff
@@ -191,13 +204,13 @@ function submitPullRequests(projectName, filesObject) {
...
   if (req.method === "POST") {
     let values = req.body.values;
-    let nomineeJSON, sdgNumber, evidenceText, sortedSubmission;
+    let nomineeJSON, sortedSubmission;
 
     // Exclude contact information from pull request
     delete values["contact"];
 
     // Parse SDG information
-    values = getSDGRelevanceInfo(values, sdgNumber, evidenceText);
```
Comment (lacabra) [inline pages/api/openPR.js:200]: @nathanbaleeta: you were essentially passing empty values. instead of initializing these variables in the main function and passing them empty, these are no longer passed and initialized only where they are used

File: pages/api/openPR.js [hunk 2]
```diff
@@ -45,16 +45,29 @@ function createGithubCheckoutBranch(name) {
...
-    sdgNumber = parseInt(values.SDGs[i]);
-    evidenceText = "evidenceText".concat(sdgNumber);
+    let sdgNumber = parseInt(values.SDGs[i]);
+    let evidenceText = "evidenceText".concat(sdgNumber);
+    let evidenceURL = "evidenceURL".concat(sdgNumber);
+
+    // Initialize the object in the array where it exists
     values.SDGs[i] = {
       SDGNumber: sdgNumber,
-      evidenceText: values[evidenceText],
```
Comment (lacabra) [inline pages/api/openPR.js:55]: @nathanbaleeta: so in the original function, you were only parsing evidenceText, but there was no mention of evidenceURL

File: pages/api/openPR.js [hunk 3]
```diff
@@ -45,16 +45,29 @@ function createGithubCheckoutBranch(name) {
...
     };
-    delete values[evidenceText];
```
Comment (lacabra) [inline pages/api/openPR.js:57]: @nathanbaleeta: and because you were only deleting `evidenceText`, but not deleting `evidenceURL`; that's why they were appearing in the DPG submissions and causing the CI to fail there.

**Review by nathanbaleeta — APPROVED** [review]
Thank you @lacabra for debugging this root cause. The changes look good to me.
