### PR TITLE
BUG:  conditional statements for PII section

### LINKED ISSUE #46: Privacy & Security Question Bug
I was looking through the form today and I found a bug on the questions for indicator 9a re: PII data. 
& 1) It didn’t ask about sharing third party data as listed in the [questionary](https://github.com/DPGAlliance/DPG-Standard/blob/main/standard-questions.md) “If yes - does this project share this data with third parties? Please describe the circumstances with which this project shares data with third parties. Please add links as relevant.” 

2) appears to cut off the question about ensuring security and privacy (see image)
Screen Shot 2021-07-28 at 11 45 36 AM

### PR DESCRIPTION
**Pull request by nathanfletcher**
This PR Fixes #46 

- The form question, in particular, has been formatted properly.
- 
Screenshot 2021-09-07 at 5 13 42 PM

- There was a bug in how the questions were displayed, in that some conditional questions were not showing up at all
- Those conditional questions have been fixed according to the schema

### CODE REVIEW

File: schemas/schema.js [hunk 1]
```diff
@@ -1458,7 +1458,7 @@ const schema = {
               ],
             },
             {
-              name: "dataPrivacySecurity[typesOfDataCollected]",
+              name: "doNoHarm[dataPrivacySecurity[typesOfDataCollected]]",
```
Comment (nathanfletcher) [inline schemas/schema.js:1461]: @lacabra this line may address the bug that was breaking the build.
This is because `"dataPrivacySecurity": {"typesOfDataCollected": []}` has now been put under the `doNoHarm` key in the schema here

Comment (lacabra) [reply schemas/schema.js:1461]: Excellent, thank you

**Review by lacabra — APPROVED** [review]
Looks good to me
